version: '3'

services:

  web-app-bff:
    build:
      context: ./src_bff
    ports:
      - "8080:8080"
    volumes:
      - ./src_bff/src:/app
    networks:
      - web-app-bff-network
      - web-app-allmusic-network
  
  web-app-allmusic:
    build:
      context: ./src_allmusic
    ports:
      - "8081:8081"
    volumes:
      - ./src_allmusic/src:/app
    networks:
      - web-app-allmusic-network
    depends_on:
      - db-allmusic
    links:
      - db-allmusic
  
  web-app-users:
    build:
      context: ./src_users
    ports:
      - "8082:8082"
    depends_on:
      - db-users
    links:
      - db-users
    volumes:
      - ./src_users/src:/app
    networks:
      - web-app-users-network
  
  db-allmusic:
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_DB: allmusic_db
      POSTGRES_USER: allmusic_user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata_allmusic_db:/var/lib/postgresql/data
    networks:
      - web-app-allmusic-network
    
  db-users:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: users_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata_users_db:/data/db
    networks:
      - web-app-users-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@home.com
      PGADMIN_DEFAULT_PASSWORD: Qwerty12345
    ports:
      - "5050:80"
    depends_on:
      - db-allmusic
    links:
      - db-allmusic
    volumes:
      - pgadmin_allmusic_db_data:/var/lib/pgadmin
    networks:
      - web-app-allmusic-network

networks:
  web-app-bff-network:
  web-app-allmusic-network:
  web-app-users-network:

volumes:
  pgdata_allmusic_db:
  pgadmin_allmusic_db_data:
  mongodata_users_db:
